version: "3.9"
services:
  nginx:
    image: rleutz/nginx:1.0
    build: ./nginx-rleutz
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-public:/srv/http
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/letsencrypt/etc:/etc/letsencrypt
      - ./nginx/letsencrypt/lib:/var/lib/letsencrypt
    links:
      - php8-fpm
      - php7-fpm
      - php5-fpm
      - mariadb-master
  php8-fpm:
    image: php:8.0-fpm
    volumes:
      - ./nginx-public:/srv/http
  php7-fpm:
    image: php:7.4-fpm
    volumes:
      - ./nginx-public:/srv/http
  php5-fpm:
    image: php:5.6-fpm
    volumes:
      - ./nginx-public:/srv/http
  mariadb-master:
    image: mariadb:10.5
    container_name: mariadb
    restart: 'on-failure'
    environment:
       MYSQL_ROOT_PASSWORD: Uware!Db2Docker
    volumes:
       - ./mariadb/master:/var/lib/mysql
